import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomTabs from "@/components/layout/BottomTabs";
import HeaderComponent from "@/components/layout/HeaderComponent";
import LayoutProviders from "@/components/layout/LayoutProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Linko",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
        <div>
          <LayoutProviders>
            <HeaderComponent/>
              {children}
            <BottomTabs />
          </LayoutProviders>
        </div>
      </body>
    </html>
  );
}
